# Generated by Django 4.2.7 on 2023-12-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('Imagen', models.ImageField(upload_to='')),
                ('Ingredientes', models.CharField(max_length=300, verbose_name='Ingredientes')),
                ('Preparacion', models.CharField(max_length=500, verbose_name='Preparacion')),
            ],
        ),
    ]
