# Generated by Django 4.2.7 on 2023-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='Descripcion',
            field=models.CharField(max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
