# Generated by Django 4.2.7 on 2023-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_receta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='Imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
