# Generated by Django 4.2.7 on 2023-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
