# Generated by Django 4.2.7 on 2023-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='Imagen',
            field=models.ImageField(upload_to='web/static/web/imagenes/recetas/'),
        ),
    ]
